version: '3.5'

services:
  reactjs_client:
      build: client/test-app/.
      ports:
        - 3000:3000
      networks:
        custom_net:
          ipv4_address: 10.5.0.2

  nodejs_server:
    build: server/.
    ports: 
      - 5001:5001
    networks:
      custom_net:
        ipv4_address: 10.5.0.3

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      custom_net:
        ipv4_address: 10.5.0.4
    restart: unless-stopped
  
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - 5050:80
  #   networks:
  #     custom_net:
  #       ipv4_address: 10.5.0.5
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
    postgres:
    pgadmin:
    nodejs_server: